name: Python Code Quality

on:
  push:
    branches: [main]
    paths:
      - "**.py"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
  workflow_dispatch: # Allow manual trigger

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy pylint

      - name: Check formatting with Black
        run: |
          black --check --diff .

      - name: Check import order with isort
        run: |
          isort --profile black --check --diff .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

      - name: Check code quality with pylint
        run: |
          pylint --disable=C0103,C0111,C0303,W1201,W1202 --fail-under=7.0 $(git ls-files '*.py')

      # - name: Type check with mypy
      #   run: |
      #     mypy --ignore-missing-imports .
